
version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: openpaymentdb
      MYSQL_USER: ustbsheila
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
  medexpense-explore-web-app:
    build:
      context: .
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - mysql
