
version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: openpaymentdb
      MYSQL_USER: ustbsheila
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
  open-payments-web-app:
    build:
      context: .
    ports:
      - "5000:5000"